// @ts-nocheck
// 由 tauri-specta 生成，请勿手改。
// 重新生成: cargo test -p launchkeeper-app export_bindings
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Every task with its derived status. */
	listTasks: () => typedError<TaskView[], AppError>(__TAURI_INVOKE("list_tasks")),
	/**  One task, with the editable form value and its timestamps. */
	getTask: (name: string) => typedError<TaskDetail, AppError>(__TAURI_INVOKE("get_task", { name })),
	/**  Creates a task in the database. launchd is untouched until `set_enabled`. */
	createTask: (input: TaskInput) => typedError<TaskView, AppError>(__TAURI_INVOKE("create_task", { input })),
	/**
	 *  Updates a task. When it is enabled, core rewrites the plist and reloads
	 *  launchd *before* touching the database, so a rejected schedule leaves
	 *  everything as it was.
	 */
	updateTask: (name: string, input: TaskInput) => typedError<TaskView, AppError>(__TAURI_INVOKE("update_task", { name, input })),
	/**  Removes the task, its plist, its launchd job, its rows and its logs. */
	deleteTask: (name: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_task", { name })),
	/**  Loads the task into launchd (writing its plist) or boots it out. */
	setEnabled: (name: string, enabled: boolean) => typedError<TaskView, AppError>(__TAURI_INVOKE("set_enabled", { name, enabled })),
	/**
	 *  Runs the task now.
	 * 
	 *  An enabled task is kickstarted through launchd, so the run happens in the
	 *  same environment a scheduled run would. A disabled task has no launchd
	 *  job to kickstart, so the runner is spawned directly with `--manual`; the
	 *  run is not waited on, and its own logging records it.
	 * 
	 *  For a service, "run it now" is "start it" — [`start_service`] — because
	 *  there is nothing else it could mean.
	 */
	runNow: (name: string) => typedError<null, AppError>(__TAURI_INVOKE("run_now", { name })),
	/**
	 *  Starts a service, loading it into launchd first if it is not loaded yet.
	 * 
	 *  Blocking for as long as `launchctl` takes, which is why — like every
	 *  command here — the work happens off the main thread.
	 */
	startService: (name: string) => typedError<TaskView, AppError>(__TAURI_INVOKE("start_service", { name })),
	/**
	 *  Stops a running service and leaves the job loaded, so that
	 *  [`start_service`] can bring it back without rewriting the plist.
	 * 
	 *  This one can block for up to [`launchkeeper_core::service::STOP_GRACE`]
	 *  waiting for the process to go away — harmless on the blocking pool, and
	 *  the reason this is an `async` command rather than a synchronous one.
	 */
	stopService: (name: string) => typedError<TaskView, AppError>(__TAURI_INVOKE("stop_service", { name })),
	/**  Stops a service and starts it again. */
	restartService: (name: string) => typedError<TaskView, AppError>(__TAURI_INVOKE("restart_service", { name })),
	/**  The newest `limit` runs of a task, newest first. */
	listRuns: (name: string, limit: number) => typedError<RunView[], AppError>(__TAURI_INVOKE("list_runs", { name, limit })),
	/**
	 *  The last `tail_bytes` bytes of one of a run's two log files.
	 * 
	 *  `tail_bytes == 0`, or anything above it, means [`MAX_TAIL_BYTES`]. The
	 *  read is byte-oriented and then decoded lossily, so a cut in the middle of
	 *  a multi-byte character yields a replacement character instead of an error.
	 */
	readLog: (runId: RunHandle, stream: LogStream, tailBytes: number) => typedError<LogChunk, AppError>(__TAURI_INVOKE("read_log", { runId, stream, tailBytes })),
	/**
	 *  Every interpreter worth offering for `script`, best first
	 *  (`docs/M3-design.md` §1).
	 * 
	 *  `script` is the script the form currently points at — it decides the
	 *  recommendation and whether 直接执行 is on the list at all — and
	 *  `project_dir` is the form's working directory, where the walk for `.venv`
	 *  / `uv.lock` / `package.json` starts. Both may be absent while the user is
	 *  still typing; the result is then just "what is installed on this machine".
	 * 
	 *  The `PATH` searched is [`env::effective_path`], i.e. the login shell's,
	 *  which is the one the runner will hand the script — not the bare
	 *  `/usr/bin:/bin:…` launchd gives this process.
	 * 
	 *  Versions are collected (one `--version` per program, cached for the life
	 *  of the process), which is why this runs on the blocking pool like every
	 *  other command.
	 */
	scanInterpreters: (script: string | null, projectDir: string | null) => typedError<InterpreterView[], AppError>(__TAURI_INVOKE("scan_interpreters", { script, projectDir })),
	/**
	 *  What the form needs to know about a script path before it will save it.
	 * 
	 *  Two questions, one round trip, asked once on save rather than on every
	 *  keystroke: does it exist (a path that is merely mistyped becomes a task
	 *  that fails silently at 21:00), and is it executable (with no interpreter
	 *  selected, launchd has to `exec` the file itself — if it cannot, the job
	 *  never starts and the only trace is a launchd error nobody reads).
	 */
	checkScript: (path: string) => typedError<ScriptCheck, AppError>(__TAURI_INVOKE("check_script", { path })),
	/**
	 *  Absolute path of the directory holding a task's per-run logs. The UI uses
	 *  it for "reveal in Finder".
	 */
	taskLogDir: (name: string) => typedError<string, AppError>(__TAURI_INVOKE("task_log_dir", { name })),
	/**
	 *  Reveals `path` in Finder.
	 * 
	 *  `open -R` rather than the opener plugin: the plugin reveals a file only
	 *  when it exists, and the UI also wants to point at a log directory that a
	 *  task has not written to yet — `open -R` on a directory selects it in its
	 *  parent, which is the behaviour the "在 Finder 中显示" menu item promises.
	 * 
	 *  The path must be absolute, and it is passed after `--`, so that nothing
	 *  the frontend hands over can be read by `open` as an option (M3).
	 */
	revealInFinder: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal_in_finder", { path })),
	/**
	 *  Every LaunchAgent in `~/Library/LaunchAgents` that Launchkeeper did not
	 *  create, sorted by label.
	 * 
	 *  Deliberately *not* part of the background scan: see the note at the top of
	 *  this section.
	 */
	listExternalAgents: () => typedError<ExternalAgentView[], AppError>(__TAURI_INVOKE("list_external_agents")),
	/**
	 *  The diff [`adopt_agent`] would apply. Read-only: nothing is written and
	 *  nothing is loaded, which is what makes it safe to fetch just to show it.
	 */
	adoptionPlan: (label: string) => typedError<AdoptionPlanView, AppError>(__TAURI_INVOKE("adoption_plan", { label })),
	/**
	 *  Takes an external LaunchAgent under management, in place.
	 * 
	 *  `reload = false` rewrites the plist and records the task but leaves
	 *  launchd's loaded copy alone — the unticked 「接管后立即重新加载」 — so a
	 *  job that must not be interrupted right now keeps running under its old
	 *  definition until the next login.
	 * 
	 *  Returns the new task's view, so the caller can select it in the list
	 *  without a round trip.
	 */
	adoptAgent: (label: string, reload: boolean) => typedError<TaskView, AppError>(__TAURI_INVOKE("adopt_agent", { label, reload })),
	/**
	 *  Undoes an adoption: the original plist comes back byte for byte from its
	 *  `.bak` and the task row goes. Log files on disk are kept.
	 */
	unadoptTask: (name: string) => typedError<null, AppError>(__TAURI_INVOKE("unadopt_task", { name })),
	/**
	 *  Loads an unmanaged LaunchAgent into launchd, or boots it out. Its plist is
	 *  never touched — this is the one thing Launchkeeper does to somebody else's
	 *  file without changing it.
	 */
	externalSetEnabled: (label: string, enabled: boolean) => typedError<ExternalAgentView, AppError>(__TAURI_INVOKE("external_set_enabled", { label, enabled })),
	/**
	 *  `launchctl kickstart` on an unmanaged label.
	 * 
	 *  No run is recorded — without the runner in `ProgramArguments` there is
	 *  nothing to record it, which is precisely what adoption fixes.
	 * 
	 *  The label is looked up in `~/Library/LaunchAgents` first, exactly as
	 *  [`external_set_enabled`] does: this command reaches launchd with a string
	 *  the frontend chose, and "kickstart whatever happens to answer to that
	 *  name" is not a thing to do to a machine's launchd. A label with no plist
	 *  of ours behind it is [`launchkeeper_core::Error::AgentNotFound`], not a
	 *  launchctl error the user has to decode.
	 */
	externalRun: (label: string) => typedError<null, AppError>(__TAURI_INVOKE("external_run", { label })),
	/**  The current settings, `AppSettings::default()` on a fresh install. */
	getSettings: () => typedError<AppSettings, AppError>(__TAURI_INVOKE("get_settings")),
	/**
	 *  Replaces the settings wholesale and returns them back, so the frontend
	 *  can update its store from the same round trip rather than assuming the
	 *  write succeeded.
	 * 
	 *  When the language changed, the tray menu is rebuilt from here (M3 §5).
	 *  The frontend re-renders itself the moment the user clicks — it owns its
	 *  own dictionaries — but the menu bar's strings come from Rust, and the
	 *  scan loop only rebuilds the menu when something about a *task* changed,
	 *  which might not happen for hours.
	 */
	setSettings: (settings: AppSettings) => typedError<AppSettings, AppError>(__TAURI_INVOKE("set_settings", { settings })),
	/**
	 *  The data directory's absolute path, for the 设置 sheet's read-only
	 *  display (`docs/M3-design.md` §4). Not editable from the app —
	 *  `LAUNCHKEEPER_DATA_DIR` / `~/.config/launchkeeper/data-dir` are for
	 *  machines where the default (`~/Library/Application Support/Launchkeeper`)
	 *  is not where the user wants it, and neither is a setting `settings.json`
	 *  itself could ever live inside — the file finds its own directory before
	 *  there is a directory to read it from.
	 */
	dataDir: () => typedError<string, AppError>(__TAURI_INVOKE("data_dir")),
	/**
	 *  The non-secret AI configuration (`<data_dir>/ai.json`). Never carries the
	 *  API key — [`has_ai_api_key`] is how the panel knows whether one is set.
	 */
	getAiConfig: () => typedError<AiConfig, AppError>(__TAURI_INVOKE("get_ai_config")),
	/**
	 *  Replaces the AI configuration and hands it back, so the panel updates
	 *  from the same round trip instead of assuming the write landed —
	 *  `set_settings` does the same.
	 */
	setAiConfig: (config: AiConfig) => typedError<AiConfig, AppError>(__TAURI_INVOKE("set_ai_config", { config })),
	/**
	 *  Stores the API key in the macOS key file.
	 * 
	 *  The key crosses the IPC bridge exactly once, on its way in, and is never
	 *  returned by any command — not by [`get_ai_config`], not by
	 *  [`has_ai_api_key`]. The panel's field is write-only for the same reason
	 *  the CLI refuses to take a key as an argument.
	 */
	setAiApiKey: (key: string) => typedError<null, AppError>(__TAURI_INVOKE("set_ai_api_key", { key })),
	/**
	 *  Whether a key can be found at all — the key file entry, or the
	 *  `LAUNCHKEEPER_AI_API_KEY` override. What the panel's 「已配置 / 未配置」
	 *  line asks.
	 */
	hasAiApiKey: () => typedError<boolean, AppError>(__TAURI_INVOKE("has_ai_api_key")),
	/**
	 *  Deletes the key file entry. Cannot clear the environment override — that
	 *  belongs to whoever started the app.
	 */
	clearAiApiKey: () => typedError<null, AppError>(__TAURI_INVOKE("clear_ai_api_key")),
	/**
	 *  「测试连接」: one short ping to the configured endpoint, answering with the
	 *  model's reply. Exercises the exact request shape [`explain_task`] uses, so
	 *  a green test really does mean 解读 will work.
	 */
	testAiConnection: () => typedError<string, AppError>(__TAURI_INVOKE("test_ai_connection")),
	/**
	 *  Explains a task, storing the answer.
	 * 
	 *  `refresh = false` returns what is already stored without calling the
	 *  model, which is what opening the 「AI 解读」 tab does; the 「重新解读」
	 *  button passes `true`.
	 * 
	 *  This is the one command in the app that can take tens of seconds. It runs
	 *  on the blocking pool like every other command (`docs/M2-design.md` §3.2),
	 *  so the window and the background scan keep going while it waits — and the
	 *  service mutex is held only for the database reads and the final write,
	 *  not for the HTTP request, because [`launchkeeper_core::Service::explain_task`]
	 *  does the gathering and the storing around a call that owns no lock of its
	 *  own.
	 */
	explainTask: (name: string, refresh: boolean) => typedError<InsightView, AppError>(__TAURI_INVOKE("explain_task", { name, refresh })),
	/**
	 *  The stored explanation of a task, or `null` when it has never been
	 *  explained. A plain read: no network, no key needed, so the tab can render
	 *  last week's answer on a machine that is offline.
	 */
	getTaskInsight: (name: string) => typedError<{
	/**  Task this explains. */
	task_name: string,
	/**  RFC 3339, UTC. */
	created_at: string,
	/**  Model that produced it, so the pane can say what wrote this. */
	model: string,
	/**  sha256 of the prompt behind `content`. */
	prompt_hash: string,
	/**  The answer, Markdown. */
	content: string,
} | null, AppError>(__TAURI_INVOKE("get_task_insight", { name })),
	/**  Version and build facts for the 关于 block. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Opens an `http://` / `https://` URL in the default browser. */
	openUrl: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("open_url", { url })),
};

/** Events */
export const events = {
	tasksChanged: makeEvent<TasksChanged>("tasks-changed"),
};

/* Types */
/**
 *  What adoption would do to one plist, key by key — the dialog's whole
 *  content, so that nobody accepts a rewrite of their own file unseen.
 */
export type AdoptionPlanView = {
	/**  The label, which adoption does not change. */
	label: string,
	/**  The task name the adopted job would get (equal to the label). */
	name: string,
	/**  The plist that would be rewritten, abbreviated. */
	path: string,
	/**  Where the original bytes go first, abbreviated. */
	backup_path: string,
	/**  Keys the rewrite drops, with their current values. */
	removed: DiffEntry[],
	/**  Keys it adds or changes, with their new values. */
	added: DiffEntry[],
	/**  Keys that come through untouched. */
	kept: DiffEntry[],
};

/**
 *  The non-secret half of the AI configuration: `<data_dir>/ai.json`.
 * 
 *  Deliberately *not* in the app's `settings.json`: the CLI has no business
 *  reading a file whose other half is about tray icons and notification
 *  checkboxes, and the app has no business owning a setting the CLI must be
 *  able to change. One small file in the shared data directory, with the same
 *  `LAUNCHKEEPER_DATA_DIR` override everything else follows.
 * 
 *  The API key is **not** here — see [`get_api_key`].
 */
export type AiConfig = {
	/**  Which wire format the endpoint speaks. */
	provider?: AiProvider,
	/**
	 *  Endpoint root. `None` means [`AiProvider::default_base_url`]. A
	 *  trailing slash is tolerated.
	 */
	base_url?: string | null,
	/**  Model id, passed through verbatim. */
	model?: string,
};

/**  Which wire format to speak. */
export type AiProvider = 
/**  Anthropic's Messages API (`POST <base>/v1/messages`). */
"anthropic" | 
/**
 *  Anything that speaks OpenAI chat completions
 *  (`POST <base>/chat/completions`): OpenAI itself, Ollama, vLLM,
 *  OpenRouter, a corporate gateway.
 * 
 *  Renamed explicitly: `rename_all = "snake_case"` would spell this
 *  `open_ai_compatible`, and the wire value has to match what
 *  [`AiProvider::as_str`] writes into `ai.json`, `--json` and the CLI's
 *  `--provider`.
 */
"openai_compatible";

/**  A command failure, as the frontend receives it. */
export type AppError = {
	/**  Human-readable, already-localised message. */
	message: string,
};

/**  What the 关于 block shows. */
export type AppInfo = {
	/**  Cargo package version of the app crate, e.g. `0.1.0`. */
	version: string,
};

/**
 *  Everything the 设置 sheet can change today.
 * 
 *  `#[serde(default)]` on the struct (via `Default`) means a `settings.json`
 *  written by an older version of the app — missing a field this version
 *  added — still parses: the missing field takes its default rather than
 *  failing the whole read.
 */
export type AppSettings = {
	/**
	 *  Post a macOS notification when a scheduled task's run finishes with a
	 *  nonzero exit code, is killed by a timeout, or otherwise ends badly —
	 *  see [`crate::notify`]. Still gated per task by
	 *  [`launchkeeper_core::Task::notify_on_fail`].
	 */
	notify_on_task_failure?: boolean,
	/**
	 *  Same, for a `KeepAlive` service crashing and being restarted by
	 *  launchd.
	 */
	notify_on_service_crash?: boolean,
	/**
	 *  UI language override: `"zh-CN"`, `"en"`, or `"system"` / `None` to
	 *  follow the system language (PRD M3 item 5, `docs/M3-design.md` §5).
	 * 
	 *  Read by the frontend on start (`src/lib/i18n`) and by
	 *  [`crate::i18n::Lang::from_settings`] for the tray menu and the
	 *  notifications. Anything this version does not recognise is treated as
	 *  "follow the system" rather than as an error — a hand-edited
	 *  `settings.json` must not be able to leave the app without a language.
	 */
	language?: string | null,
	/**
	 *  How the 「Launchkeeper 管理」 group is sorted: `"name"`,
	 *  `"last_run"`, `"status"` or `"next_run"` (PRD M4 item 2,
	 *  `docs/M4-design.md` §2). `None` means the default, `"name"`.
	 * 
	 *  Rust never reads the value — the list is sorted in the frontend, which
	 *  is also where the four modes are defined (`src/lib/sort.ts`). This
	 *  field exists only so the choice outlives the window, which is why an
	 *  unrecognised string is not an error here either: `sortMode()` on the
	 *  frontend maps anything it does not know back to `"name"`.
	 */
	list_sort?: string | null,
	/**
	 *  Appearance: `"system"`, `"light"` or `"dark"` (`docs/M4-design.md`
	 *  §4). `None` means the default, `"system"` — follow macOS.
	 * 
	 *  Like `list_sort`, Rust never reads this: the frontend stamps
	 *  `data-theme` on `<html>` and asks the Tauri window for a matching
	 *  title bar (`src/lib/theme.ts`). It lives here so the choice outlives
	 *  the window, and an unrecognised string falls back to "follow the
	 *  system" on the frontend rather than failing the read here — the same
	 *  rule `language` follows.
	 */
	theme?: string | null,
};

/**  One `StartCalendarInterval` entry. Absent fields mean "every". */
export type CalendarEntry = {
	/**  Minute, 0-59. */
	minute: number,
	/**  Hour, 0-23. */
	hour: number,
	/**  Weekday 0-7; both 0 and 7 mean Sunday (launchd semantics). */
	weekday: number | null,
	/**  Day of month, 1-31. */
	day: number | null,
};

/**
 *  One line of the adoption diff: a plist key and its value, flattened to a
 *  single string by [`launchkeeper_core::agents::value_text`].
 */
export type DiffEntry = {
	/**  The plist key. */
	key: string,
	/**  Its value, on one line. */
	value: string,
};

/**
 *  One environment variable. A list of these rather than a map, because
 *  TypeScript records lose ordering and make an editable form awkward.
 */
export type EnvVar = {
	/**  Variable name. */
	key: string,
	/**  Variable value. */
	value: string,
};

/**
 *  One LaunchAgent Launchkeeper did not write, as the list and the read-only
 *  detail pane render it.
 * 
 *  Every string is composed here rather than in the frontend, for the reason
 *  [`InterpreterView`] gives: the CLI's `agents` table and this pane must not
 *  describe the same plist two different ways.
 */
export type ExternalAgentView = {
	/**
	 *  The launchd label — the identity adoption deliberately preserves. It
	 *  is also this view's key: the commands below all take it.
	 */
	label: string,
	/**  The plist file, with `$HOME` abbreviated to `~`. */
	path: string,
	/**
	 *  The same file, absolute — what 在 Finder 中显示 has to be given, since
	 *  `reveal_in_finder` (rightly) refuses anything that is not an absolute
	 *  path and cannot expand a `~` the frontend wrote.
	 */
	full_path: string,
	/**  Program plus arguments as one line. */
	command: string,
	/**
	 *  The trigger in Chinese, or 不支持的触发方式 when the plist's
	 *  scheduling keys do not translate into Launchkeeper's model.
	 */
	trigger_text: string,
	/**
	 *  The structured trigger when the plist's scheduling keys translate
	 *  into Launchkeeper's model; `None` otherwise. The frontend describes
	 *  it in the UI language (`lib/describeTrigger.ts`) instead of showing
	 *  the Chinese `trigger_text`.
	 */
	trigger: Trigger | null,
	/**  `WorkingDirectory`, abbreviated. */
	working_dir: string | null,
	/**
	 *  `StandardOutPath`, abbreviated. Shown as 日志 in the read-only detail:
	 *  adoption stops using it, so the user should know where it was.
	 */
	stdout_path: string | null,
	/**  `StandardErrorPath`, abbreviated. */
	stderr_path: string | null,
	/**  `KeepAlive` in either of its shapes. */
	keep_alive: boolean,
	/**  launchd knows this label right now. */
	loaded: boolean,
	/**  Pid, while the job has a process. */
	pid: number | null,
	/**  The exit code launchd remembers for it. */
	last_exit: number | null,
	/**  Adoption would work. `false` greys the row out. */
	adoptable: boolean,
	/**  Why not, when `adoptable` is false — the row's tooltip. */
	adopt_reason: string | null,
	/**
	 *  Already Launchkeeper's: an adopted task's plist, or a
	 *  `com.launchkeeper.*` label. Such rows are listed (core keeps them so
	 *  that the flag has a value at all) but never offered for adoption.
	 */
	managed: boolean,
};

/**
 *  One stored explanation, as the detail pane renders it.
 * 
 *  `created_at` is an RFC 3339 string rather than a number so the frontend
 *  can hand it straight to `Date`, the same convention `RunView` follows.
 */
export type InsightView = {
	/**  Task this explains. */
	task_name: string,
	/**  RFC 3339, UTC. */
	created_at: string,
	/**  Model that produced it, so the pane can say what wrote this. */
	model: string,
	/**  sha256 of the prompt behind `content`. */
	prompt_hash: string,
	/**  The answer, Markdown. */
	content: string,
};

/**
 *  Which section of the 运行方式 picker an entry belongs to
 *  (`docs/M3-design.md` §1).
 */
export type InterpreterGroup = 
/**  推荐 — the one entry `scan` picked, and only that one. */
"recommended" | 
/**  项目内 — a `.venv` belonging to the script's own project. */
"project" | 
/**  PATH 里的其他解释器 — everything else, including 直接执行. */
"path";

/**  What kind of program runs the script. */
export type InterpreterKind = 
/**  `python3` / `python`, including a project's `.venv/bin/python`. */
"python" | 
/**  `uv run <script>`. */
"uv" | 
/**  `node`. */
"node" | 
/**  `bun`. */
"bun" | 
/**  `deno run <script>`. */
"deno" | 
/**  `ruby`. */
"ruby" | 
/**  `zsh` / `bash` / `sh`. */
"shell" | 
/**
 *  No interpreter at all: launchd executes the script itself, which
 *  requires it to be executable and to carry a shebang.
 */
"direct" | 
/**  A path the user typed in by hand. */
"custom";

/**
 *  One row of the 运行方式 picker.
 * 
 *  The strings are all built on the Rust side ([`Interpreter::display_name`],
 *  [`Interpreter::detail`]) so that the picker, the list row's
 *  `interpreter_label` and the CLI cannot describe the same interpreter three
 *  different ways.
 */
export type InterpreterView = {
	/**
	 *  Stable identity for the `<select>`-alike: the program plus its prefix
	 *  args ([`Interpreter::id`]).
	 */
	id: string,
	/**
	 *  Which family this is; the frontend needs it to know that `direct`
	 *  composes differently from everything else.
	 */
	kind: InterpreterKind,
	/**  Absolute path of the program (the script itself, for `direct`). */
	program: string,
	/**  Arguments that precede the script, e.g. `["run"]`. */
	prefix_args: string[],
	/**  Parsed `--version` output, when the program answered in time. */
	version: string | null,
	/**  Where it came from. */
	origin: Origin,
	/**  The bold part of a row: `python3`, `uv run`, `直接执行`. */
	label: string,
	/**  The muted part: `3.9.6 · 系统 /usr/bin/python3`. */
	detail: string,
	/**  True for the single recommended entry. */
	recommended: boolean,
	/**
	 *  Why it is recommended; rendered as the one-line note under the
	 *  dropdown. Only set on the recommended entry.
	 */
	reason: string | null,
	/**  Which section it renders under. */
	group: InterpreterGroup,
};

/**  The tail of one log file. */
export type LogChunk = {
	/**  The tail, lossily decoded as UTF-8. */
	content: string,
	/**  Size of the whole file on disk. */
	total_bytes: number,
	/**  True when `content` is only the tail of a larger file. */
	truncated: boolean,
};

/**  Which of a run's two captured streams to read. */
export type LogStream = 
/**  The script's standard output. */
"stdout" | 
/**  The script's standard error. */
"stderr";

/**
 *  Where an interpreter came from. Shown next to the version so that two
 *  `python3`s are told apart by something other than their paths.
 */
export type Origin = 
/**  `/usr/bin`, `/bin`, `/usr/sbin`, `/sbin` — shipped with macOS. */
"system" | 
/**
 *  `/opt/homebrew` or `/usr/local`, *and* that prefix really has a
 *  `bin/brew` in it — otherwise the path is just another `PATH` entry
 *  (`/usr/local/bin` is where plenty of non-Homebrew installers land).
 */
"homebrew" | 
/**  `<project>/.venv/bin`. */
"project_venv" | 
/**  `~/.local/bin/uv` itself: uv's own installer put it there. */
"uv" | 
/**
 *  Anything else in `~/.local/bin` — a user-level install, not
 *  necessarily uv's doing (pipx, `pip install --user`, a hand-made
 *  symlink).
 */
"user_local" | 
/**  Anywhere else on `PATH`. */
"path" | 
/**  Typed in by the user, or the script itself for [`InterpreterKind::Direct`]. */
"custom";

/**
 *  A run's row id, as it crosses the bridge.
 * 
 *  A named newtype rather than a bare `i64` because `#[specta(type = ...)]`
 *  only applies to struct fields, not to command arguments — and `read_log`
 *  needs one. It also makes `RunView.id` and `read_log`'s parameter provably
 *  the same thing.
 */
export type RunHandle = number;

/**
 *  One recorded execution, as the frontend sees it. Timestamps are RFC 3339
 *  strings so the frontend can hand them straight to `Date`.
 */
export type RunView = {
	/**  Row id; the handle `read_log` takes. */
	id: RunHandle,
	/**  RFC 3339, UTC. */
	started_at: string,
	/**  RFC 3339, UTC. `None` while the run is in flight. */
	finished_at: string | null,
	/**  Exit code. `None` with `finished_at` set means killed by a signal. */
	exit_code: number | null,
	/**  Wall-clock duration, `None` while running. */
	duration_ms: number | null,
	/**  launchd-triggered or user-triggered. */
	trigger_kind: TriggerKind,
	/**
	 *  Why the run ended. `None` while it is still going, and on rows a
	 *  pre-M2.5 runner wrote.
	 */
	stop_reason: StopReason | null,
	/**  True while `finished_at` is unset. */
	running: boolean,
};

/**  The answer to [`check_script`]. */
export type ScriptCheck = {
	/**  The path resolves to something. */
	exists: boolean,
	/**
	 *  A regular file with an execute bit — i.e. something launchd could
	 *  start on its own. Note that this is deliberately *not* "executable
	 *  and carrying a shebang", which is what `scan_interpreters` requires
	 *  before offering 直接执行: a compiled binary has no shebang and runs
	 *  perfectly well, and the CLI has always accepted one
	 *  (`--script /bin/echo`).
	 */
	executable: boolean,
};

/**
 *  Why a run ended. Stored in `runs.stop_reason`; `None` on rows a v1 runner
 *  wrote and on runs that have not finished yet.
 */
export type StopReason = 
/**  The script finished on its own, for whatever exit code. */
"exited" | 
/**
 *  The runner was asked to stop (SIGTERM / SIGINT, e.g. `launchctl kill
 *  TERM` behind [`crate::Service::stop`]) and terminated the script.
 */
"stopped" | 
/**  The run exceeded `timeout_secs` and the script was killed. */
"timeout";

/**
 *  The detail pane's payload: the editable form value, the two timestamps
 *  that are not editable, and the same [`TaskView`] the list holds.
 */
export type TaskDetail = {
	/**  The editable fields. */
	task: TaskInput,
	/**  RFC 3339, UTC. */
	created_at: string,
	/**  RFC 3339, UTC. */
	updated_at: string,
	/**  Derived, read-only view. */
	view: TaskView,
	/**
	 *  This task came from somebody else's LaunchAgent (M3 §3.1). The detail
	 *  pane says so, and offers 撤销接管.
	 */
	adopted: boolean,
	/**
	 *  The plist this task lives in when it was adopted — its original file,
	 *  which adoption did not move. `None` for tasks Launchkeeper created,
	 *  whose plist is derived from the name.
	 */
	plist_path: string | null,
};

/**
 *  Everything the editor form can set. Used both as `create_task` /
 *  `update_task` input and, inside [`TaskDetail`], as the form's initial
 *  value — so the two never drift apart.
 */
export type TaskInput = {
	/**  Unique name; `^[a-z0-9][a-z0-9.-]{0,63}$`. */
	name: string,
	/**  Human-facing name. */
	display_name: string,
	/**  Optional longer description. */
	description: string | null,
	/**  Absolute path to the script or executable. */
	script_path: string,
	/**  Arguments passed to it. */
	args: string[],
	/**  Working directory; `$HOME` when unset. */
	working_dir: string | null,
	/**  Extra environment variables. */
	env: EnvVar[],
	/**  When it runs. */
	trigger: Trigger,
	/**
	 *  launchd `KeepAlive`; only valid with [`Trigger::AtLogin`] or
	 *  [`Trigger::Manual`]. `Task::validate` enforces that, so an invalid
	 *  combination comes back as an error from `create_task`/`update_task`
	 *  rather than being silently dropped.
	 */
	keep_alive: boolean,
	/**  Per-run wall-clock limit in seconds. */
	timeout_secs: number | null,
	/**  Free-form tags. */
	tags: string[],
	/**  Pinned to the menu bar. */
	favorite: boolean,
	/**  Post a notification when a run fails. */
	notify_on_fail: boolean,
};

/**
 *  The status dot in the task list.
 * 
 *  For a scheduled task, decided exactly as `docs/M2-design.md` §3.3 spells
 *  out, in this order: not enabled → `Disabled`; newest run still running →
 *  `Running`; no run at all → `Never`; exit code 0 → `Ok`; anything else →
 *  `Failed`.
 * 
 *  A service ([`launchkeeper_core::Task::is_service`]) is decided from
 *  launchd's answer instead, because "is it up right now?" is the only
 *  question that matters for one: not enabled → `Disabled`; launchd reports a
 *  pid → `Running`; otherwise `Stopped`, unless the last run ended badly and
 *  `keep_alive` is on — a crash loop — which is `Failed`.
 * 
 *  There is deliberately no `Restarting`: a crash-looping service is
 *  `Failed`, and the row's own text (exit code, stop reason, last-run time)
 *  says what is happening. One more colour of dot would not.
 */
export type TaskStatus = 
/**  Last run succeeded. */
"ok" | 
/**  Last run failed, timed out or was killed. */
"failed" | 
/**  A run is in flight. */
"running" | 
/**  Enabled but never run. */
"never" | 
/**  Not loaded into launchd. */
"disabled" | 
/**  A service that is loaded but not running right now. */
"stopped";

/**  A task as the list renders it. */
export type TaskView = {
	/**  Unique name (also the launchd label suffix). */
	name: string,
	/**  Human-facing name. */
	display_name: string,
	/**  Optional longer description. */
	description: string | null,
	/**  Structured trigger, for the editor. */
	trigger: Trigger,
	/**  `Trigger::describe()`, for the list row. */
	trigger_text: string,
	/**
	 *  How the task runs, as one line: `python3 · 系统`, `uv run · uv 安装`,
	 *  `直接执行`. Derived from the stored `script_path` + `args` by
	 *  [`launchkeeper_core::interpreters::detect_from_task`], so it costs
	 *  nothing but string work and needs no filesystem access — the picker's
	 *  full scan happens only when the form is open.
	 */
	interpreter_label: string | null,
	/**
	 *  [`Task::is_service`]: a `Manual` task, driven by start/stop rather
	 *  than by a schedule. The list row and the detail header switch their
	 *  whole set of controls on this.
	 */
	is_service: boolean,
	/**
	 *  launchd `KeepAlive`. On a service it means "restart after a crash,
	 *  stay down after a manual stop", and it is what makes `Failed` mean
	 *  "crash-looping" rather than "ended badly once".
	 */
	keep_alive: boolean,
	/**  Plist present *and* launchd knows the label. */
	enabled: boolean,
	/**  Pid of the running job, when launchd reports one. */
	loaded_pid: number | null,
	/**
	 *  Seconds since the run that is still in flight started. `None` unless
	 *  launchd reports a pid *and* the newest run has no `finished_at` — for
	 *  a service, that is its uptime.
	 */
	uptime_secs: number | null,
	/**  Newest run, when there is one. */
	last_run: RunView | null,
	/**  Free-form tags. */
	tags: string[],
	/**  Pinned to the menu bar. */
	favorite: boolean,
	/**
	 *  Post a notification when a run fails ([`TaskInput::notify_on_fail`]).
	 *  The list row never shows this directly, but [`crate::notify`] needs
	 *  it on the same value the scan loop already produces, rather than a
	 *  second database read per task per scan.
	 */
	notify_on_fail: boolean,
	/**  The status dot. */
	status: TaskStatus,
};

/**
 *  Emitted after every background scan (`docs/M2-design.md` §3.4). The
 *  frontend re-renders from this instead of polling `list_tasks` itself.
 */
export type TasksChanged = 
/**  Every task, in the same order and shape `list_tasks` returns. */
TaskView[];

/**
 *  When a task should run: the three shapes launchd schedules, plus
 *  [`Trigger::Manual`] for a long-running service the user starts and stops
 *  by hand.
 */
export type Trigger = 
/**  `RunAtLoad`: fires when the agent is loaded (i.e. at login). */
{ kind: "at_login" } | 
/**  `StartInterval`: every `seconds` seconds. */
{ kind: "interval"; 
/**  Interval in seconds, at least 1. */
seconds: number } | 
/**  `StartCalendarInterval`: one or more wall-clock rules. */
{ kind: "calendar"; 
/**  Non-empty list of calendar rules. */
entries: CalendarEntry[] } | 
/**
 *  No automatic trigger at all: the plist carries none of `RunAtLoad` /
 *  `StartInterval` / `StartCalendarInterval`, and the job only ever runs
 *  because someone called [`crate::Service::start`] (i.e. `launchctl
 *  kickstart`).
 * 
 *  Combined with `keep_alive` this is a service: launchd writes
 *  `KeepAlive = {SuccessfulExit = false}`, which — measured on real
 *  launchd, see `docs/M2.5-design.md` §3.1 — also makes `bootstrap`
 *  start the job immediately.
 */
{ kind: "manual" };

/**  Why a run happened. */
export type TriggerKind = 
/**  launchd started it. */
"scheduled" | 
/**  The user asked for it. */
"manual";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

