#!/usr/bin/env bash
# Builds the CLI + runner in release mode and packs them into the tarball the
# GitHub release carries:
#
#   target/release/dist/launchkeeper-cli-<version>-<triple>.tar.gz
#   target/release/dist/launchkeeper-cli-<version>-<triple>.tar.gz.sha256
#
# Layout inside the tarball (a plain prefix directory, so `tar -xzf` into
# /usr/local or a keg both work, and the two binaries stay siblings — which is
# exactly the layout `resolve_runner_source` looks for):
#
#   launchkeeper-cli-<version>-<triple>/
#     bin/launchkeeper
#     bin/launchkeeper-runner
#     completions/{launchkeeper.bash,_launchkeeper,launchkeeper.fish}
#     LICENSE
#
# This is *not* what the Homebrew Formula installs — that one builds from the
# source tarball with cargo (see packaging/homebrew/Formula/launchkeeper.rb).
# This tarball is for people who just want the binaries.
set -euo pipefail

repo_root=$(cd "$(dirname "$0")/../.." && pwd)
cd "$repo_root"

command -v cargo >/dev/null 2>&1 || { echo "找不到 cargo" >&2; exit 1; }

version=$(awk '/^\[workspace\.package\]/{f=1;next} /^\[/{f=0} f && /^version[[:space:]]*=/{gsub(/[",]/,"",$3); print $3; exit}' Cargo.toml)
[ -n "$version" ] || { echo "无法解析 version" >&2; exit 1; }
triple=$(rustc -vV | awk '/^host:/{print $2}')

cargo build --release --bin launchkeeper --bin launchkeeper-runner

name="launchkeeper-cli-$version-$triple"
out="$repo_root/target/release/dist"
stage="$out/$name"
rm -rf "$stage"
mkdir -p "$stage/bin" "$stage/completions"

cp "target/release/launchkeeper" "target/release/launchkeeper-runner" "$stage/bin/"
cp LICENSE "$stage/"

# Generated by the binary just built, so the completions can never drift from
# the flags they complete.
"$stage/bin/launchkeeper" completions bash >"$stage/completions/launchkeeper.bash"
"$stage/bin/launchkeeper" completions zsh >"$stage/completions/_launchkeeper"
"$stage/bin/launchkeeper" completions fish >"$stage/completions/launchkeeper.fish"

tarball="$out/$name.tar.gz"
rm -f "$tarball" "$tarball.sha256"
tar -czf "$tarball" -C "$out" "$name"
(cd "$out" && shasum -a 256 "$name.tar.gz" >"$name.tar.gz.sha256")
rm -rf "$stage"

echo "$tarball"
cat "$tarball.sha256"
